apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fitness-kv-secrets
  namespace: fitness
spec:
  provider: azure

  secretObjects:
  - secretName: fitness-app-secrets
    type: Opaque
    data:
    - objectName: mongodb-uri
      key: mongodb-uri
    - objectName: node-env
      key: node-env
    - objectName: port
      key: port
    - objectName: host
      key: host
    - objectName: jwt-secret
      key: jwt-secret

  parameters:
    usePodIdentity: "false"
    clientID: "a797f484-fb59-4245-917b-2d5c2505ccfb"
    keyvaultName: "shubha-aks-kv"
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"

    objects: |
      array:
        - |
          objectName: mongodb-uri
          objectType: secret
        - |
          objectName: node-env
          objectType: secret
        - |
          objectName: port
          objectType: secret
        - |
          objectName: host
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret